name: Docker Image CI and Test

on:
  push:
    branches: [ docker-test ]
  pull_request:
    branches: [ master ]

env:
  CINC2023_REVENGER_TEST: 1
  # revenger_data_dir: ${{ github.workspace }}/training_data
  # revenger_model_dir: ${{ github.workspace }}/models
  # revenger_test_dir: ${{ github.workspace }}/test
  # revenger_output_dir: ${{ github.workspace }}/output
  download_data_dir: ${{ github.workspace }}/download_data
  revenger_data_dir: /challenge/training_data
  revenger_model_dir: /challenge/models
  revenger_test_dir: /challenge/test
  revenger_output_dir: /challenge/output
  # docker_filename: test.Dockerfile
  docker_filename: Dockerfile

jobs:

  build:
    if: contains(fromJson('["wenh06", "kjs11", "DeepPSP"]'), github.repository_owner)

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build the Docker image
      run: docker build . --file ${{ env.docker_filename }} --tag deeppsp-cinc2023-docker-image:latest

    - name: Download the training_subset data
      run: |
        mkdir -p ${{ env.download_data_dir }}
        docker run \
          -e CINC2023_REVENGER_TEST=${{ env.CINC2023_REVENGER_TEST }} \
          -e revenger_data_dir=${{ env.revenger_data_dir }} \
          -v ${{ env.download_data_dir }}:${{ env.revenger_data_dir }} \
          deeppsp-cinc2023-docker-image:latest \
          bash -c "python data_reader.py download --db-dir ${{ env.revenger_data_dir }}"
        docker ps -a
        docker stop $(docker ps -a -q)

    - name: Run the Docker image
      # skip if env.docker_filename is 'test.Dockerfile'
      # NOTE: mount env.download_data_dir to env.revenger_data_dir
      # and set it read-only as the CinC2023 challenge setting
      if: ${{ env.docker_filename == 'Dockerfile' }}
      run: |
        docker run \
          -e CINC2023_REVENGER_TEST=${{ env.CINC2023_REVENGER_TEST }} \
          -e revenger_data_dir=${{ env.revenger_data_dir }} \
          -e revenger_model_dir=${{ env.revenger_model_dir }} \
          -e revenger_test_dir=${{ env.revenger_test_dir }} \
          -e revenger_output_dir=${{ env.revenger_output_dir }} \
          -v ${{ env.download_data_dir }}:${{ env.revenger_data_dir }}:ro \
          deeppsp-cinc2023-docker-image:latest \
          bash -c "bash test_run_challenge.sh"
        docker ps -a
        docker stop $(docker ps -a -q)
